name: gpm
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/generic-package-manager/gpm

environment:
  sdk: ^3.2.3


dependencies:
  archive: ^3.6.1
  args: ^2.4.2
  chalkdart: ^2.2.1
  cli_spin: ^1.0.1
  cli_table: ^1.0.2
  http: ^1.2.0
  intl: ^0.19.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
